name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest

    name: RuboCop
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop --color

  tests:
    runs-on: ubuntu-latest

    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run RSpec
        run: bundle exec rspec
